# -*- coding: utf-8 -*-
"""password strength checker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gl3ul31BASAWTeVPAy8CzN-FKviNLtVO
"""

import re

def check_password_strength(password):
    strength = 0

    # length check
    if len(password) >= 8:
        strength += 1

    # contains both lower & upper case
    if re.search(r"[a-z]", password) and re.search(r"[A-Z]", password):
        strength += 1

    # contains numbers
    if re.search(r"[0-9]", password):
        strength += 1

    # contains special characters
    if re.search(r"[@$!%*?&#]", password):
        strength += 1

    # final decision
    if strength == 4:
        return "Strong 💪"
    elif strength == 3:
        return "Medium 🙂"
    else:
        return "Weak ❌"

# test
password = input("Enter your password: ")
print("Password strength:", check_password_strength(password))

